### PR TITLE
make the webserver optional

### PR DESCRIPTION
**Pull request by jsecchiero**

### CODE REVIEW

**Review by davepanarese — CHANGES_REQUESTED** [review]
move icingaweb2_webserver variable under ICINGAWEB2 VARIABLE SECTION (bottom of file)

**Comment by jsecchiero** [comment]
Hi Davide, try this!
let me know.
Jacopo

**Comment by jsecchiero** [comment]
What's wrong this time?
Jacopo

**Comment by jsecchiero** [comment]
ping ;)

**Pull request merged**
